# Generated by Django 4.1.2 on 2025-08-20 03:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Germination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("active", "Active")],
                        max_length=20,
                    ),
                ),
                ("germination_rate", models.PositiveIntegerField()),
                ("test_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                ("for_year", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GerminationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=10)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GermSamplePrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("print_date", models.DateField(default=django.utils.timezone.now)),
                ("for_year", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Grower",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("smarties_ct", models.PositiveIntegerField(default=0)),
                ("inv_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("harvest", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "external_lot_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("low_inv", models.BooleanField(default=False)),
                (
                    "grower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lots",
                        to="lots.grower",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_seeds",
                        to="lots.lot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetiredLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retired_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "lbs_remaining",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retired_info",
                        to="lots.lot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField()),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="lots.lot",
                    ),
                ),
            ],
        ),
    ]
