# Generated by Django 4.1.2 on 2025-08-20 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lots", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="variety",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="products.variety",
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="lots.lot",
            ),
        ),
        migrations.AddField(
            model_name="germsampleprint",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="germ_sample_prints",
                to="lots.lot",
            ),
        ),
        migrations.AddField(
            model_name="germination",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="germinations",
                to="lots.germinationbatch",
            ),
        ),
        migrations.AddField(
            model_name="germination",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="germinations",
                to="lots.lot",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockseed",
            unique_together={("lot", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="lot",
            unique_together={("variety", "grower", "year", "harvest")},
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("lot", "inv_date")},
        ),
        migrations.AlterUniqueTogether(
            name="germsampleprint",
            unique_together={("lot", "print_date")},
        ),
        migrations.AlterUniqueTogether(
            name="germination",
            unique_together={("lot", "test_date")},
        ),
    ]
