# Generated by Django 4.1.2 on 2025-08-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germination",
            name="test_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
