# Generated by Django 4.1.2 on 2025-08-29 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0003_alter_germination_test_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germinationbatch",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
