# Generated by Django 4.1.2 on 2025-08-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0004_alter_germinationbatch_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germinationbatch",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
