# Generated by Django 5.2.5 on 2025-09-17 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0005_alter_germinationbatch_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Growout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "planted_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transplant_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price_per_lb",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bed_ft", models.CharField(blank=True, max_length=100, null=True)),
                ("amt_sown", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growout_info",
                        to="lots.lot",
                    ),
                ),
            ],
        ),
    ]
