# Generated by Django 5.2.5 on 2025-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0006_growout"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
