# Generated by Django 5.2.5 on 2025-11-26 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0007_inventory_notes"),
        ("products", "0006_variety_is_mix"),
    ]

    operations = [
        migrations.CreateModel(
            name="MixLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot_code", models.CharField(max_length=10)),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mix_lots",
                        to="products.variety",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "unique_together": {("variety", "lot_code")},
            },
        ),
        migrations.CreateModel(
            name="MixBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("final_weight", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "mix_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="lots.mixlot",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MixLotComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts", models.PositiveIntegerField()),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_mixes",
                        to="lots.lot",
                    ),
                ),
                (
                    "mix_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="lots.mixlot",
                    ),
                ),
                (
                    "sub_mix_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_as_component",
                        to="lots.mixlot",
                    ),
                ),
            ],
        ),
    ]
