# Generated by Django 5.2.5 on 2025-11-26 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0008_mixlot_mixbatch_mixlotcomponent"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetiredMixLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retired_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "mix_lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retired_mix_info",
                        to="lots.mixlot",
                    ),
                ),
            ],
        ),
    ]
