# Generated by Django 5.2.5 on 2026-01-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0009_retiredmixlot"),
        ("products", "0012_remove_variety_veg_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrowoutPrep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("quantity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price_per_lb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("lot_created", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prep_record",
                        to="lots.lot",
                    ),
                ),
                (
                    "grower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="growout_preps",
                        to="lots.grower",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growout_preps",
                        to="products.variety",
                    ),
                ),
            ],
            options={
                "ordering": ["variety__var_name", "-year", "grower__code"],
            },
        ),
    ]
