# Generated by Django 5.2.5 on 2026-03-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0010_growoutprep"),
    ]

    operations = [
        migrations.AddField(
            model_name="growout",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="growout",
            name="planted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="growout",
            name="transplant_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
