# Generated by Django 4.1.2 on 2025-08-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficeSupply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=255)),
                ("item_num", models.CharField(blank=True, max_length=100, null=True)),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "office_supplies",
            },
        ),
    ]
