# Generated by Django 4.1.2 on 2025-08-20 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("store_num", models.IntegerField(primary_key=True, serialize=False)),
                ("store_name", models.CharField(default="default", max_length=100)),
                (
                    "store_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "store_contact_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("store_contact_email", models.TextField(blank=True, null=True)),
                ("store_address", models.TextField(blank=True, null=True)),
                ("store_address2", models.TextField(blank=True, null=True)),
                ("store_city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "store_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("store_zip", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "store_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rack_material",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rack_num", models.CharField(blank=True, max_length=100, null=True)),
                ("header", models.CharField(blank=True, max_length=100, null=True)),
                ("velcro", models.BooleanField(default=False)),
                (
                    "first_order",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("slots", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="StoreProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stores.store"
                    ),
                ),
            ],
            options={
                "unique_together": {("store", "product")},
            },
        ),
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(default="XXXXX-XX", max_length=100, unique=True),
                ),
                ("date", models.DateTimeField()),
                ("fulfilled_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="stores.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoreNote",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("note", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="stores.store",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="available_products",
            field=models.ManyToManyField(
                related_name="available_in_stores",
                through="stores.StoreProduct",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="store_user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SOIncludes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "store_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stores.storeorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "SO Include",
                "verbose_name_plural": "SO Includes",
            },
        ),
        migrations.CreateModel(
            name="LastSelectedStore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_selected_store",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
