# Generated by Django 5.2.5 on 2025-08-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeorder",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
