# Generated by Django 5.2.5 on 2025-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_alter_storeorder_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="soincludes",
            name="photo",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
