# Generated by Django 5.2.5 on 2025-10-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_soincludes_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickListPrinted",
            fields=[
                (
                    "store_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pick_list_record",
                        serialize=False,
                        to="stores.storeorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pick List Print Record",
                "verbose_name_plural": "Pick List Print Records",
            },
        ),
    ]
