# Generated by Django 5.2.5 on 2025-10-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_picklistprinted"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="shipping",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
