# Generated by Django 5.2.5 on 2025-10-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_storeorder_shipping"),
    ]

    operations = [
        migrations.CreateModel(
            name="WholesalePktPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                (
                    "price_per_packet",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
            ],
            options={
                "verbose_name": "Wholesale Packet Price",
                "verbose_name_plural": "Wholesale Packet Prices",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="StoreReturns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "return_year",
                    models.IntegerField(
                        help_text="Year the packets were returned (e.g., 2024)"
                    ),
                ),
                (
                    "packets_returned",
                    models.IntegerField(
                        default=0, help_text="Number of packets returned by store"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Return",
                "verbose_name_plural": "Store Returns",
                "ordering": ["-return_year"],
                "unique_together": {("store", "return_year")},
            },
        ),
    ]
