# Generated by Django 5.2.5 on 2026-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_wholesalepktprice_storereturns"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="quickbooks_invoice",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
