# Generated by Django 4.1.2 on 2025-08-20 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_identifier", models.CharField(max_length=100, unique=True)),
                ("batch_date", models.DateField()),
                ("start_order_number", models.IntegerField()),
                ("end_order_number", models.IntegerField()),
                ("start_order_date", models.DateField()),
                ("end_order_date", models.DateField()),
            ],
            options={
                "db_table": "batch_metadata",
            },
        ),
        migrations.CreateModel(
            name="OnlineOrder",
            fields=[
                (
                    "order_number",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("address2", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "shipping",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateTimeField()),
                ("bulk", models.BooleanField(default=False)),
                ("misc", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "online_order",
            },
        ),
        migrations.CreateModel(
            name="LastSelected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_selected_order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "last_selected",
            },
        ),
        migrations.CreateModel(
            name="BulkBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bulk_type", models.CharField(max_length=50)),
                ("sku", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                (
                    "batch_identifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_batches",
                        to="orders.batchmetadata",
                    ),
                ),
            ],
            options={
                "db_table": "bulk_batch",
            },
        ),
        migrations.CreateModel(
            name="OOIncludesMisc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("qty", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="includes_misc",
                        to="orders.onlineorder",
                    ),
                ),
            ],
            options={
                "db_table": "oo_includes_misc",
                "unique_together": {("order", "sku")},
            },
        ),
        migrations.CreateModel(
            name="OOIncludes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="includes",
                        to="orders.onlineorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "oo_includes",
                "unique_together": {("order", "product")},
            },
        ),
    ]
