# Generated by Django 5.2.5 on 2025-09-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlineorder",
            name="shipping_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
