# Generated by Django 4.1.2 on 2025-08-20 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lots", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiscProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lineitem_name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pkg_size", models.CharField(blank=True, max_length=50, null=True)),
                ("sku_suffix", models.CharField(blank=True, max_length=50, null=True)),
                ("alt_sku", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "lineitem_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rack_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("env_type", models.CharField(blank=True, max_length=50, null=True)),
                ("env_multiplier", models.IntegerField(blank=True, null=True)),
                ("label", models.CharField(blank=True, max_length=1, null=True)),
                ("num_printed", models.IntegerField(blank=True, null=True)),
                ("num_printed_next_year", models.IntegerField(default=0)),
                ("scoop_size", models.CharField(blank=True, max_length=50, null=True)),
                ("print_back", models.BooleanField(default=False)),
                (
                    "bulk_pre_pack",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("is_sub_product", models.BooleanField(default=False)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="lots.lot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variety",
            fields=[
                (
                    "sku_prefix",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("var_name", models.CharField(blank=True, max_length=255, null=True)),
                ("crop", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "common_spelling",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "common_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("group", models.CharField(blank=True, max_length=255, null=True)),
                ("veg_type", models.CharField(blank=True, max_length=255, null=True)),
                ("species", models.CharField(blank=True, max_length=255, null=True)),
                ("supergroup", models.CharField(blank=True, max_length=255, null=True)),
                ("subtype", models.CharField(blank=True, max_length=255, null=True)),
                ("days", models.CharField(blank=True, max_length=50, null=True)),
                ("active", models.BooleanField(default=True)),
                ("stock_qty", models.CharField(blank=True, max_length=50, null=True)),
                ("photo_path", models.CharField(blank=True, max_length=255, null=True)),
                ("wholesale", models.BooleanField(default=False)),
                ("desc_line1", models.TextField(blank=True, null=True)),
                ("desc_line2", models.TextField(blank=True, null=True)),
                ("desc_line3", models.TextField(blank=True, null=True)),
                ("back1", models.TextField(blank=True, null=True)),
                ("back2", models.TextField(blank=True, null=True)),
                ("back3", models.TextField(blank=True, null=True)),
                ("back4", models.TextField(blank=True, null=True)),
                ("back5", models.TextField(blank=True, null=True)),
                ("back6", models.TextField(blank=True, null=True)),
                ("back7", models.TextField(blank=True, null=True)),
                ("ws_notes", models.TextField(blank=True, null=True)),
                ("ws_description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VarWholeSaleNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wholesale_notes_list",
                        to="products.variety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VarNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="products.variety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("year", models.IntegerField()),
                ("wholesale", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rad_type", models.CharField(max_length=100)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rad_type",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="variety",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.variety",
            ),
        ),
        migrations.CreateModel(
            name="MiscSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lbs", models.FloatField()),
                ("date", models.DateField()),
                ("customer", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc_sales",
                        to="products.variety",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LastSelected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_selected_for",
                        to="products.variety",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Last Selected",
            },
        ),
        migrations.CreateModel(
            name="InitialProductOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("tracked", models.BooleanField(default=False)),
                ("initial_offering", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initial_offerings",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Growout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sow_date", models.DateField()),
                ("start_date", models.DateField()),
                ("harvest_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "variety",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growout_info",
                        to="products.variety",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("variety", "sku_suffix")},
        ),
    ]
