# Generated by Django 4.1.2 on 2025-08-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0003_alter_germination_test_date"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("qty", models.IntegerField()),
                ("for_year", models.IntegerField()),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_prints",
                        to="lots.lot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_prints",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
