# Generated by Django 5.2.5 on 2025-11-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_miscsales"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="website_bulk",
            field=models.BooleanField(default=False),
        ),
    ]
