# Generated by Django 5.2.5 on 2025-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_variety_website_bulk"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="wholesale_rack_designation",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
