# Generated by Django 5.2.5 on 2025-11-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_variety_wholesale_rack_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="is_mix",
            field=models.BooleanField(default=False),
        ),
    ]
