# Generated by Django 5.2.5 on 2025-11-26 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0008_mixlot_mixbatch_mixlotcomponent"),
        ("products", "0006_variety_is_mix"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="mix_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="lots.mixlot",
            ),
        ),
    ]
