# Generated by Django 5.2.5 on 2025-11-26 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0008_mixlot_mixbatch_mixlotcomponent"),
        ("products", "0007_product_mix_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelprint",
            name="mix_lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_prints",
                to="lots.mixlot",
            ),
        ),
    ]
