# Generated by Django 5.2.5 on 2025-12-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_labelprint_mix_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="growout_needed",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
