# Generated by Django 5.2.5 on 2025-12-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_variety_growout_needed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variety",
            name="supergroup",
        ),
    ]
