# Generated by Django 5.2.5 on 2025-12-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_variety_supergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="variety",
            name="var_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
