# Generated by Django 5.2.5 on 2026-01-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_variety_var_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variety",
            name="veg_type",
        ),
    ]
